org: gcoutini
app: wumpus-world
service: wumpus-world-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  wumpus:
    handler: src/handler.wumpus
    events:
      - httpApi:
          path: /wumpus
          method: post

plugins:
  - serverless-offline
